// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var speedracer_fb = speedracer_fb || {};

/**
 * @enum
 */
speedracer_fb.DataBufferFormat = {
  BUFFER_NONE: 0,
  BUFFER_RGB_8: 1,
  BUFFER_RGBA_8: 2,
  BUFFER_UINT_16_LE: 3,
  BUFFER_UINT_16_BE: 4,
  BUFFER_FLOAT_32_LE: 5
};

/**
 * @constructor
 */
speedracer_fb.Vector3f = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.Vector3f}
 */
speedracer_fb.Vector3f.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
speedracer_fb.Vector3f.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
speedracer_fb.Vector3f.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
speedracer_fb.Vector3f.prototype.z = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.Vector3f.createVector3f = function(builder, x, y, z) {
  builder.prep(4, 12);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
speedracer_fb.Color3f = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.Color3f}
 */
speedracer_fb.Color3f.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
speedracer_fb.Color3f.prototype.r = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
speedracer_fb.Color3f.prototype.g = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
speedracer_fb.Color3f.prototype.b = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} r
 * @param {number} g
 * @param {number} b
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.Color3f.createColor3f = function(builder, r, g, b) {
  builder.prep(4, 12);
  builder.writeFloat32(b);
  builder.writeFloat32(g);
  builder.writeFloat32(r);
  return builder.offset();
};

/**
 * @constructor
 */
speedracer_fb.Matrix4f = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.Matrix4f}
 */
speedracer_fb.Matrix4f.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {speedracer_fb.Vector3f=} obj
 * @returns {speedracer_fb.Vector3f|null}
 */
speedracer_fb.Matrix4f.prototype.basisX = function(obj) {
  return (obj || new speedracer_fb.Vector3f).__init(this.bb_pos, this.bb);
};

/**
 * @param {speedracer_fb.Vector3f=} obj
 * @returns {speedracer_fb.Vector3f|null}
 */
speedracer_fb.Matrix4f.prototype.basisY = function(obj) {
  return (obj || new speedracer_fb.Vector3f).__init(this.bb_pos + 12, this.bb);
};

/**
 * @param {speedracer_fb.Vector3f=} obj
 * @returns {speedracer_fb.Vector3f|null}
 */
speedracer_fb.Matrix4f.prototype.t = function(obj) {
  return (obj || new speedracer_fb.Vector3f).__init(this.bb_pos + 24, this.bb);
};

/**
 * @returns {number}
 */
speedracer_fb.Matrix4f.prototype.s = function() {
  return this.bb.readFloat32(this.bb_pos + 36);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} basis_x_x
 * @param {number} basis_x_y
 * @param {number} basis_x_z
 * @param {number} basis_y_x
 * @param {number} basis_y_y
 * @param {number} basis_y_z
 * @param {number} t_x
 * @param {number} t_y
 * @param {number} t_z
 * @param {number} s
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.Matrix4f.createMatrix4f = function(builder, basis_x_x, basis_x_y, basis_x_z, basis_y_x, basis_y_y, basis_y_z, t_x, t_y, t_z, s) {
  builder.prep(4, 40);
  builder.writeFloat32(s);
  builder.prep(4, 12);
  builder.writeFloat32(t_z);
  builder.writeFloat32(t_y);
  builder.writeFloat32(t_x);
  builder.prep(4, 12);
  builder.writeFloat32(basis_y_z);
  builder.writeFloat32(basis_y_y);
  builder.writeFloat32(basis_y_x);
  builder.prep(4, 12);
  builder.writeFloat32(basis_x_z);
  builder.writeFloat32(basis_x_y);
  builder.writeFloat32(basis_x_x);
  return builder.offset();
};

/**
 * @constructor
 */
speedracer_fb.Viewport = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.Viewport}
 */
speedracer_fb.Viewport.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
speedracer_fb.Viewport.prototype.width = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @returns {number}
 */
speedracer_fb.Viewport.prototype.height = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} width
 * @param {number} height
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.Viewport.createViewport = function(builder, width, height) {
  builder.prep(4, 8);
  builder.writeInt32(height);
  builder.writeInt32(width);
  return builder.offset();
};

/**
 * @constructor
 */
speedracer_fb.BoundingBox2i = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.BoundingBox2i}
 */
speedracer_fb.BoundingBox2i.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox2i.prototype.xmin = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox2i.prototype.xmax = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox2i.prototype.ymin = function() {
  return this.bb.readInt32(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox2i.prototype.ymax = function() {
  return this.bb.readInt32(this.bb_pos + 12);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} xmin
 * @param {number} xmax
 * @param {number} ymin
 * @param {number} ymax
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.BoundingBox2i.createBoundingBox2i = function(builder, xmin, xmax, ymin, ymax) {
  builder.prep(4, 16);
  builder.writeInt32(ymax);
  builder.writeInt32(ymin);
  builder.writeInt32(xmax);
  builder.writeInt32(xmin);
  return builder.offset();
};

/**
 * @constructor
 */
speedracer_fb.BoundingBox3f = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.BoundingBox3f}
 */
speedracer_fb.BoundingBox3f.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox3f.prototype.xmin = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox3f.prototype.xmax = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox3f.prototype.ymin = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox3f.prototype.ymax = function() {
  return this.bb.readFloat32(this.bb_pos + 12);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox3f.prototype.zmin = function() {
  return this.bb.readFloat32(this.bb_pos + 16);
};

/**
 * @returns {number}
 */
speedracer_fb.BoundingBox3f.prototype.zmax = function() {
  return this.bb.readFloat32(this.bb_pos + 20);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} xmin
 * @param {number} xmax
 * @param {number} ymin
 * @param {number} ymax
 * @param {number} zmin
 * @param {number} zmax
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.BoundingBox3f.createBoundingBox3f = function(builder, xmin, xmax, ymin, ymax, zmin, zmax) {
  builder.prep(4, 24);
  builder.writeFloat32(zmax);
  builder.writeFloat32(zmin);
  builder.writeFloat32(ymax);
  builder.writeFloat32(ymin);
  builder.writeFloat32(xmax);
  builder.writeFloat32(xmin);
  return builder.offset();
};

/**
 * @constructor
 */
speedracer_fb.DataBuffer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.DataBuffer}
 */
speedracer_fb.DataBuffer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {speedracer_fb.DataBuffer=} obj
 * @returns {speedracer_fb.DataBuffer}
 */
speedracer_fb.DataBuffer.getRootAsDataBuffer = function(bb, obj) {
  return (obj || new speedracer_fb.DataBuffer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {speedracer_fb.DataBufferFormat}
 */
speedracer_fb.DataBuffer.prototype.format = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {speedracer_fb.DataBufferFormat} */ (this.bb.readInt8(this.bb_pos + offset)) : speedracer_fb.DataBufferFormat.BUFFER_NONE;
};

/**
 * @param {number} index
 * @returns {number}
 */
speedracer_fb.DataBuffer.prototype.data = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
speedracer_fb.DataBuffer.prototype.dataLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
speedracer_fb.DataBuffer.prototype.dataArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
speedracer_fb.DataBuffer.startDataBuffer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {speedracer_fb.DataBufferFormat} format
 */
speedracer_fb.DataBuffer.addFormat = function(builder, format) {
  builder.addFieldInt8(0, format, speedracer_fb.DataBufferFormat.BUFFER_NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
speedracer_fb.DataBuffer.addData = function(builder, dataOffset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.DataBuffer.createDataVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
speedracer_fb.DataBuffer.startDataVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.DataBuffer.endDataBuffer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
speedracer_fb.FrameID = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.FrameID}
 */
speedracer_fb.FrameID.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {speedracer_fb.FrameID=} obj
 * @returns {speedracer_fb.FrameID}
 */
speedracer_fb.FrameID.getRootAsFrameID = function(bb, obj) {
  return (obj || new speedracer_fb.FrameID).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
speedracer_fb.FrameID.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
speedracer_fb.FrameID.startFrameID = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
speedracer_fb.FrameID.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.FrameID.endFrameID = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
speedracer_fb.ImageFragmentBuffers = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.ImageFragmentBuffers}
 */
speedracer_fb.ImageFragmentBuffers.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {speedracer_fb.ImageFragmentBuffers=} obj
 * @returns {speedracer_fb.ImageFragmentBuffers}
 */
speedracer_fb.ImageFragmentBuffers.getRootAsImageFragmentBuffers = function(bb, obj) {
  return (obj || new speedracer_fb.ImageFragmentBuffers).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {speedracer_fb.Viewport=} obj
 * @returns {speedracer_fb.Viewport|null}
 */
speedracer_fb.ImageFragmentBuffers.prototype.extents = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new speedracer_fb.Viewport).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {speedracer_fb.DataBuffer=} obj
 * @returns {speedracer_fb.DataBuffer|null}
 */
speedracer_fb.ImageFragmentBuffers.prototype.pixels = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new speedracer_fb.DataBuffer).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {speedracer_fb.DataBuffer=} obj
 * @returns {speedracer_fb.DataBuffer|null}
 */
speedracer_fb.ImageFragmentBuffers.prototype.depth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new speedracer_fb.DataBuffer).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
speedracer_fb.ImageFragmentBuffers.startImageFragmentBuffers = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} extentsOffset
 */
speedracer_fb.ImageFragmentBuffers.addExtents = function(builder, extentsOffset) {
  builder.addFieldStruct(0, extentsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pixelsOffset
 */
speedracer_fb.ImageFragmentBuffers.addPixels = function(builder, pixelsOffset) {
  builder.addFieldOffset(1, pixelsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} depthOffset
 */
speedracer_fb.ImageFragmentBuffers.addDepth = function(builder, depthOffset) {
  builder.addFieldOffset(2, depthOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.ImageFragmentBuffers.endImageFragmentBuffers = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // extents
  return offset;
};

/**
 * @constructor
 */
speedracer_fb.ImageFragmentInfo = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.ImageFragmentInfo}
 */
speedracer_fb.ImageFragmentInfo.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {speedracer_fb.ImageFragmentInfo=} obj
 * @returns {speedracer_fb.ImageFragmentInfo}
 */
speedracer_fb.ImageFragmentInfo.getRootAsImageFragmentInfo = function(bb, obj) {
  return (obj || new speedracer_fb.ImageFragmentInfo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
speedracer_fb.ImageFragmentInfo.prototype.key = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {speedracer_fb.BoundingBox2i=} obj
 * @returns {speedracer_fb.BoundingBox2i|null}
 */
speedracer_fb.ImageFragmentInfo.prototype.bounds = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new speedracer_fb.BoundingBox2i).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {boolean}
 */
speedracer_fb.ImageFragmentInfo.prototype.isOpaque = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
speedracer_fb.ImageFragmentInfo.startImageFragmentInfo = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} keyOffset
 */
speedracer_fb.ImageFragmentInfo.addKey = function(builder, keyOffset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} boundsOffset
 */
speedracer_fb.ImageFragmentInfo.addBounds = function(builder, boundsOffset) {
  builder.addFieldStruct(1, boundsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isOpaque
 */
speedracer_fb.ImageFragmentInfo.addIsOpaque = function(builder, isOpaque) {
  builder.addFieldInt8(2, +isOpaque, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.ImageFragmentInfo.endImageFragmentInfo = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
speedracer_fb.ImageFragmentList = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {speedracer_fb.ImageFragmentList}
 */
speedracer_fb.ImageFragmentList.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {speedracer_fb.ImageFragmentList=} obj
 * @returns {speedracer_fb.ImageFragmentList}
 */
speedracer_fb.ImageFragmentList.getRootAsImageFragmentList = function(bb, obj) {
  return (obj || new speedracer_fb.ImageFragmentList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {speedracer_fb.FrameID=} obj
 * @returns {speedracer_fb.FrameID|null}
 */
speedracer_fb.ImageFragmentList.prototype.frame = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new speedracer_fb.FrameID).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @param {speedracer_fb.ImageFragmentInfo=} obj
 * @returns {speedracer_fb.ImageFragmentInfo}
 */
speedracer_fb.ImageFragmentList.prototype.fragments = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new speedracer_fb.ImageFragmentInfo).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
speedracer_fb.ImageFragmentList.prototype.fragmentsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
speedracer_fb.ImageFragmentList.prototype.totalCount = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
speedracer_fb.ImageFragmentList.prototype.accumCount = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
speedracer_fb.ImageFragmentList.startImageFragmentList = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} frameOffset
 */
speedracer_fb.ImageFragmentList.addFrame = function(builder, frameOffset) {
  builder.addFieldOffset(0, frameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fragmentsOffset
 */
speedracer_fb.ImageFragmentList.addFragments = function(builder, fragmentsOffset) {
  builder.addFieldOffset(1, fragmentsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.ImageFragmentList.createFragmentsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
speedracer_fb.ImageFragmentList.startFragmentsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} totalCount
 */
speedracer_fb.ImageFragmentList.addTotalCount = function(builder, totalCount) {
  builder.addFieldInt32(2, totalCount, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} accumCount
 */
speedracer_fb.ImageFragmentList.addAccumCount = function(builder, accumCount) {
  builder.addFieldInt32(3, accumCount, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
speedracer_fb.ImageFragmentList.endImageFragmentList = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.speedracer_fb = speedracer_fb;
