/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RenderJob_constants.h"

namespace speedracer_thrift {

const RenderJobConstants g_RenderJob_constants;

RenderJobConstants::RenderJobConstants() {
}

} // namespace

