/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RenderJob_CONSTANTS_H
#define RenderJob_CONSTANTS_H

#include "RenderJob_types.h"

namespace speedracer_thrift {

class RenderJobConstants {
 public:
  RenderJobConstants();

};

extern const RenderJobConstants g_RenderJob_constants;

} // namespace

#endif
