# automatically generated by the FlatBuffers compiler, do not modify

# namespace: speedracer_fb

import flatbuffers

class BoundingBox3f(object):
    __slots__ = ['_tab']

    # BoundingBox3f
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoundingBox3f
    def Xmin(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BoundingBox3f
    def Xmax(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # BoundingBox3f
    def Ymin(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # BoundingBox3f
    def Ymax(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # BoundingBox3f
    def Zmin(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # BoundingBox3f
    def Zmax(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateBoundingBox3f(builder, xmin, xmax, ymin, ymax, zmin, zmax):
    builder.Prep(4, 24)
    builder.PrependFloat32(zmax)
    builder.PrependFloat32(zmin)
    builder.PrependFloat32(ymax)
    builder.PrependFloat32(ymin)
    builder.PrependFloat32(xmax)
    builder.PrependFloat32(xmin)
    return builder.Offset()
