# automatically generated by the FlatBuffers compiler, do not modify

# namespace: speedracer_fb

class DataBufferFormat(object):
    BUFFER_NONE = 0
    BUFFER_RGB_8 = 1
    BUFFER_RGBA_8 = 2
    BUFFER_UINT_16_LE = 3
    BUFFER_UINT_16_BE = 4
    BUFFER_FLOAT_32_LE = 5

