# automatically generated by the FlatBuffers compiler, do not modify

# namespace: speedracer_fb

import flatbuffers

class Viewport(object):
    __slots__ = ['_tab']

    # Viewport
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Viewport
    def Width(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Viewport
    def Height(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateViewport(builder, width, height):
    builder.Prep(4, 8)
    builder.PrependInt32(height)
    builder.PrependInt32(width)
    return builder.Offset()
