/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-01-23")
public class BoundingBox2i implements org.apache.thrift.TBase<BoundingBox2i, BoundingBox2i._Fields>, java.io.Serializable, Cloneable, Comparable<BoundingBox2i> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BoundingBox2i");

  private static final org.apache.thrift.protocol.TField XMIN_FIELD_DESC = new org.apache.thrift.protocol.TField("xmin", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField XMAX_FIELD_DESC = new org.apache.thrift.protocol.TField("xmax", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField YMIN_FIELD_DESC = new org.apache.thrift.protocol.TField("ymin", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField YMAX_FIELD_DESC = new org.apache.thrift.protocol.TField("ymax", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BoundingBox2iStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BoundingBox2iTupleSchemeFactory();

  public int xmin; // required
  public int xmax; // required
  public int ymin; // required
  public int ymax; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    XMIN((short)1, "xmin"),
    XMAX((short)2, "xmax"),
    YMIN((short)3, "ymin"),
    YMAX((short)4, "ymax");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // XMIN
          return XMIN;
        case 2: // XMAX
          return XMAX;
        case 3: // YMIN
          return YMIN;
        case 4: // YMAX
          return YMAX;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __XMIN_ISSET_ID = 0;
  private static final int __XMAX_ISSET_ID = 1;
  private static final int __YMIN_ISSET_ID = 2;
  private static final int __YMAX_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.XMIN, new org.apache.thrift.meta_data.FieldMetaData("xmin", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.XMAX, new org.apache.thrift.meta_data.FieldMetaData("xmax", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.YMIN, new org.apache.thrift.meta_data.FieldMetaData("ymin", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.YMAX, new org.apache.thrift.meta_data.FieldMetaData("ymax", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BoundingBox2i.class, metaDataMap);
  }

  public BoundingBox2i() {
    this.xmin = 2147483647;

    this.xmax = -2147483648;

    this.ymin = 2147483647;

    this.ymax = -2147483648;

  }

  public BoundingBox2i(
    int xmin,
    int xmax,
    int ymin,
    int ymax)
  {
    this();
    this.xmin = xmin;
    setXminIsSet(true);
    this.xmax = xmax;
    setXmaxIsSet(true);
    this.ymin = ymin;
    setYminIsSet(true);
    this.ymax = ymax;
    setYmaxIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BoundingBox2i(BoundingBox2i other) {
    __isset_bitfield = other.__isset_bitfield;
    this.xmin = other.xmin;
    this.xmax = other.xmax;
    this.ymin = other.ymin;
    this.ymax = other.ymax;
  }

  public BoundingBox2i deepCopy() {
    return new BoundingBox2i(this);
  }

  @Override
  public void clear() {
    this.xmin = 2147483647;

    this.xmax = -2147483648;

    this.ymin = 2147483647;

    this.ymax = -2147483648;

  }

  public int getXmin() {
    return this.xmin;
  }

  public BoundingBox2i setXmin(int xmin) {
    this.xmin = xmin;
    setXminIsSet(true);
    return this;
  }

  public void unsetXmin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __XMIN_ISSET_ID);
  }

  /** Returns true if field xmin is set (has been assigned a value) and false otherwise */
  public boolean isSetXmin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __XMIN_ISSET_ID);
  }

  public void setXminIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __XMIN_ISSET_ID, value);
  }

  public int getXmax() {
    return this.xmax;
  }

  public BoundingBox2i setXmax(int xmax) {
    this.xmax = xmax;
    setXmaxIsSet(true);
    return this;
  }

  public void unsetXmax() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __XMAX_ISSET_ID);
  }

  /** Returns true if field xmax is set (has been assigned a value) and false otherwise */
  public boolean isSetXmax() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __XMAX_ISSET_ID);
  }

  public void setXmaxIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __XMAX_ISSET_ID, value);
  }

  public int getYmin() {
    return this.ymin;
  }

  public BoundingBox2i setYmin(int ymin) {
    this.ymin = ymin;
    setYminIsSet(true);
    return this;
  }

  public void unsetYmin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __YMIN_ISSET_ID);
  }

  /** Returns true if field ymin is set (has been assigned a value) and false otherwise */
  public boolean isSetYmin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __YMIN_ISSET_ID);
  }

  public void setYminIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __YMIN_ISSET_ID, value);
  }

  public int getYmax() {
    return this.ymax;
  }

  public BoundingBox2i setYmax(int ymax) {
    this.ymax = ymax;
    setYmaxIsSet(true);
    return this;
  }

  public void unsetYmax() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __YMAX_ISSET_ID);
  }

  /** Returns true if field ymax is set (has been assigned a value) and false otherwise */
  public boolean isSetYmax() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __YMAX_ISSET_ID);
  }

  public void setYmaxIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __YMAX_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case XMIN:
      if (value == null) {
        unsetXmin();
      } else {
        setXmin((java.lang.Integer)value);
      }
      break;

    case XMAX:
      if (value == null) {
        unsetXmax();
      } else {
        setXmax((java.lang.Integer)value);
      }
      break;

    case YMIN:
      if (value == null) {
        unsetYmin();
      } else {
        setYmin((java.lang.Integer)value);
      }
      break;

    case YMAX:
      if (value == null) {
        unsetYmax();
      } else {
        setYmax((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case XMIN:
      return getXmin();

    case XMAX:
      return getXmax();

    case YMIN:
      return getYmin();

    case YMAX:
      return getYmax();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case XMIN:
      return isSetXmin();
    case XMAX:
      return isSetXmax();
    case YMIN:
      return isSetYmin();
    case YMAX:
      return isSetYmax();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BoundingBox2i)
      return this.equals((BoundingBox2i)that);
    return false;
  }

  public boolean equals(BoundingBox2i that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_xmin = true;
    boolean that_present_xmin = true;
    if (this_present_xmin || that_present_xmin) {
      if (!(this_present_xmin && that_present_xmin))
        return false;
      if (this.xmin != that.xmin)
        return false;
    }

    boolean this_present_xmax = true;
    boolean that_present_xmax = true;
    if (this_present_xmax || that_present_xmax) {
      if (!(this_present_xmax && that_present_xmax))
        return false;
      if (this.xmax != that.xmax)
        return false;
    }

    boolean this_present_ymin = true;
    boolean that_present_ymin = true;
    if (this_present_ymin || that_present_ymin) {
      if (!(this_present_ymin && that_present_ymin))
        return false;
      if (this.ymin != that.ymin)
        return false;
    }

    boolean this_present_ymax = true;
    boolean that_present_ymax = true;
    if (this_present_ymax || that_present_ymax) {
      if (!(this_present_ymax && that_present_ymax))
        return false;
      if (this.ymax != that.ymax)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + xmin;

    hashCode = hashCode * 8191 + xmax;

    hashCode = hashCode * 8191 + ymin;

    hashCode = hashCode * 8191 + ymax;

    return hashCode;
  }

  @Override
  public int compareTo(BoundingBox2i other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetXmin()).compareTo(other.isSetXmin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXmin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xmin, other.xmin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetXmax()).compareTo(other.isSetXmax());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXmax()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xmax, other.xmax);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetYmin()).compareTo(other.isSetYmin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYmin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ymin, other.ymin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetYmax()).compareTo(other.isSetYmax());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYmax()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ymax, other.ymax);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BoundingBox2i(");
    boolean first = true;

    sb.append("xmin:");
    sb.append(this.xmin);
    first = false;
    if (!first) sb.append(", ");
    sb.append("xmax:");
    sb.append(this.xmax);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ymin:");
    sb.append(this.ymin);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ymax:");
    sb.append(this.ymax);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BoundingBox2iStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BoundingBox2iStandardScheme getScheme() {
      return new BoundingBox2iStandardScheme();
    }
  }

  private static class BoundingBox2iStandardScheme extends org.apache.thrift.scheme.StandardScheme<BoundingBox2i> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BoundingBox2i struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // XMIN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.xmin = iprot.readI32();
              struct.setXminIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // XMAX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.xmax = iprot.readI32();
              struct.setXmaxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // YMIN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ymin = iprot.readI32();
              struct.setYminIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // YMAX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ymax = iprot.readI32();
              struct.setYmaxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BoundingBox2i struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(XMIN_FIELD_DESC);
      oprot.writeI32(struct.xmin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(XMAX_FIELD_DESC);
      oprot.writeI32(struct.xmax);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(YMIN_FIELD_DESC);
      oprot.writeI32(struct.ymin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(YMAX_FIELD_DESC);
      oprot.writeI32(struct.ymax);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BoundingBox2iTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BoundingBox2iTupleScheme getScheme() {
      return new BoundingBox2iTupleScheme();
    }
  }

  private static class BoundingBox2iTupleScheme extends org.apache.thrift.scheme.TupleScheme<BoundingBox2i> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BoundingBox2i struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetXmin()) {
        optionals.set(0);
      }
      if (struct.isSetXmax()) {
        optionals.set(1);
      }
      if (struct.isSetYmin()) {
        optionals.set(2);
      }
      if (struct.isSetYmax()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetXmin()) {
        oprot.writeI32(struct.xmin);
      }
      if (struct.isSetXmax()) {
        oprot.writeI32(struct.xmax);
      }
      if (struct.isSetYmin()) {
        oprot.writeI32(struct.ymin);
      }
      if (struct.isSetYmax()) {
        oprot.writeI32(struct.ymax);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BoundingBox2i struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.xmin = iprot.readI32();
        struct.setXminIsSet(true);
      }
      if (incoming.get(1)) {
        struct.xmax = iprot.readI32();
        struct.setXmaxIsSet(true);
      }
      if (incoming.get(2)) {
        struct.ymin = iprot.readI32();
        struct.setYminIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ymax = iprot.readI32();
        struct.setYmaxIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

