/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum DataBufferFormat implements org.apache.thrift.TEnum {
  BUFFER_NONE(0),
  BUFFER_RGB_8(1),
  BUFFER_RGBA_8(2),
  BUFFER_UINT_16_LE(3),
  BUFFER_UINT_16_BE(4),
  BUFFER_FLOAT_32_LE(5);

  private final int value;

  private DataBufferFormat(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DataBufferFormat findByValue(int value) { 
    switch (value) {
      case 0:
        return BUFFER_NONE;
      case 1:
        return BUFFER_RGB_8;
      case 2:
        return BUFFER_RGBA_8;
      case 3:
        return BUFFER_UINT_16_LE;
      case 4:
        return BUFFER_UINT_16_BE;
      case 5:
        return BUFFER_FLOAT_32_LE;
      default:
        return null;
    }
  }
}
