// automatically generated by the FlatBuffers compiler, do not modify

package speedracer_fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BoundingBox2i extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BoundingBox2i __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int xmin() { return bb.getInt(bb_pos + 0); }
  public int xmax() { return bb.getInt(bb_pos + 4); }
  public int ymin() { return bb.getInt(bb_pos + 8); }
  public int ymax() { return bb.getInt(bb_pos + 12); }

  public static int createBoundingBox2i(FlatBufferBuilder builder, int xmin, int xmax, int ymin, int ymax) {
    builder.prep(4, 16);
    builder.putInt(ymax);
    builder.putInt(ymin);
    builder.putInt(xmax);
    builder.putInt(xmin);
    return builder.offset();
  }
}

