// automatically generated by the FlatBuffers compiler, do not modify

package speedracer_fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BoundingBox3f extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BoundingBox3f __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float xmin() { return bb.getFloat(bb_pos + 0); }
  public float xmax() { return bb.getFloat(bb_pos + 4); }
  public float ymin() { return bb.getFloat(bb_pos + 8); }
  public float ymax() { return bb.getFloat(bb_pos + 12); }
  public float zmin() { return bb.getFloat(bb_pos + 16); }
  public float zmax() { return bb.getFloat(bb_pos + 20); }

  public static int createBoundingBox3f(FlatBufferBuilder builder, float xmin, float xmax, float ymin, float ymax, float zmin, float zmax) {
    builder.prep(4, 24);
    builder.putFloat(zmax);
    builder.putFloat(zmin);
    builder.putFloat(ymax);
    builder.putFloat(ymin);
    builder.putFloat(xmax);
    builder.putFloat(xmin);
    return builder.offset();
  }
}

