// automatically generated by the FlatBuffers compiler, do not modify

package speedracer_fb;

public final class DataBufferFormat {
  private DataBufferFormat() { }
  public static final byte BUFFER_NONE = 0;
  public static final byte BUFFER_RGB_8 = 1;
  public static final byte BUFFER_RGBA_8 = 2;
  public static final byte BUFFER_UINT_16_LE = 3;
  public static final byte BUFFER_UINT_16_BE = 4;
  public static final byte BUFFER_FLOAT_32_LE = 5;

  public static final String[] names = { "BUFFER_NONE", "BUFFER_RGB_8", "BUFFER_RGBA_8", "BUFFER_UINT_16_LE", "BUFFER_UINT_16_BE", "BUFFER_FLOAT_32_LE", };

  public static String name(int e) { return names[e]; }
}

