// automatically generated by the FlatBuffers compiler, do not modify

package speedracer_fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DataBuffer extends Table {
  public static DataBuffer getRootAsDataBuffer(ByteBuffer _bb) { return getRootAsDataBuffer(_bb, new DataBuffer()); }
  public static DataBuffer getRootAsDataBuffer(ByteBuffer _bb, DataBuffer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public DataBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte format() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int data(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createDataBuffer(FlatBufferBuilder builder,
      byte format,
      int dataOffset) {
    builder.startObject(2);
    DataBuffer.addData(builder, dataOffset);
    DataBuffer.addFormat(builder, format);
    return DataBuffer.endDataBuffer(builder);
  }

  public static void startDataBuffer(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addFormat(FlatBufferBuilder builder, byte format) { builder.addByte(0, format, 0); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(1, dataOffset, 0); }
  public static int createDataVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endDataBuffer(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

