// automatically generated by the FlatBuffers compiler, do not modify

package speedracer_fb;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Viewport extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Viewport __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int width() { return bb.getInt(bb_pos + 0); }
  public int height() { return bb.getInt(bb_pos + 4); }

  public static int createViewport(FlatBufferBuilder builder, int width, int height) {
    builder.prep(4, 8);
    builder.putInt(height);
    builder.putInt(width);
    return builder.offset();
  }
}

